# Generated by Django 3.1.7 on 2021-03-23 13:17

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playbook',
            name='image_product',
            field=models.ImageField(blank=True, upload_to='image_product', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])]),
        ),
    ]
